//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Script: ./scripts/cldr-relative-time.csx
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Alrev.Intl.Abstractions;
using Alrev.Intl.Abstractions.PluralRules;
using Alrev.Intl.Abstractions.RelativeTime;
using System;
using System.Collections.Generic;

namespace Alrev.Intl.RelativeTime.Resources
{
    /// <summary>
    /// <see cref="IRelativeTimeResourceSet"/> for 'Lakota' [lkt]
    /// </summary>
    public class LakotaRelativeTimeResourceSet : IRelativeTimeResourceSet, IResource
    {
        private const string LOCALE = "lkt";

        /// <summary>
        /// The <see cref="IRelativeTimeResourceSet"/> locale
        /// </summary>
        public string Locale { get; } = LOCALE;

        /// <summary>
        /// Gets Era <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Era { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Era,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Era,
                RelativeTimeStyleValues.Long,
                "Era",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Era,
                RelativeTimeStyleValues.Narrow,
                "Era",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Era,
                RelativeTimeStyleValues.Short,
                "Era",
                null,
                null,
                null));

        /// <summary>
        /// Gets Year <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Year { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Year,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Year,
                RelativeTimeStyleValues.Long,
                "Ómakȟa",
                new Dictionary<int, string> { { -1, "Ómakȟa kʼuŋ héhaŋ" }, { 0, "Lé ómakȟa kiŋ" }, { 1, "Tȟokáta ómakȟa kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta ómakȟa {0} kʼuŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ ómakȟa {0} kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Year,
                RelativeTimeStyleValues.Narrow,
                "Ómakȟa",
                new Dictionary<int, string> { { -1, "Ómakȟa kʼuŋ héhaŋ" }, { 0, "Lé ómakȟa kiŋ" }, { 1, "Tȟokáta ómakȟa kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta ómakȟa {0} kʼuŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ ómakȟa {0} kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Year,
                RelativeTimeStyleValues.Short,
                "Ómakȟa",
                new Dictionary<int, string> { { -1, "Ómakȟa kʼuŋ héhaŋ" }, { 0, "Lé ómakȟa kiŋ" }, { 1, "Tȟokáta ómakȟa kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta ómakȟa {0} kʼuŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ ómakȟa {0} kiŋháŋ" } }));

        /// <summary>
        /// Gets Quarter <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Quarter { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Quarter,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Quarter,
                RelativeTimeStyleValues.Long,
                "Quarter",
                new Dictionary<int, string> { { -1, "last quarter" }, { 0, "this quarter" }, { 1, "next quarter" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Q" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Q" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Quarter,
                RelativeTimeStyleValues.Narrow,
                "Quarter",
                new Dictionary<int, string> { { -1, "last quarter" }, { 0, "this quarter" }, { 1, "next quarter" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Q" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Q" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Quarter,
                RelativeTimeStyleValues.Short,
                "Quarter",
                new Dictionary<int, string> { { -1, "last quarter" }, { 0, "this quarter" }, { 1, "next quarter" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Q" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Q" } }));

        /// <summary>
        /// Gets Month <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Month { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Month,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Month,
                RelativeTimeStyleValues.Long,
                "Wí",
                new Dictionary<int, string> { { -1, "Wí kʼuŋ héhaŋ" }, { 0, "Lé wí kiŋ" }, { 1, "Tȟokáta wí kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta wíyawapi {0} kʼuŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ wíyawapi {0} kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Month,
                RelativeTimeStyleValues.Narrow,
                "Wí",
                new Dictionary<int, string> { { -1, "Wí kʼuŋ héhaŋ" }, { 0, "Lé wí kiŋ" }, { 1, "Tȟokáta wí kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta wíyawapi {0} kʼuŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ wíyawapi {0} kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Month,
                RelativeTimeStyleValues.Short,
                "Wí",
                new Dictionary<int, string> { { -1, "Wí kʼuŋ héhaŋ" }, { 0, "Lé wí kiŋ" }, { 1, "Tȟokáta wí kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta wíyawapi {0} kʼuŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ wíyawapi {0} kiŋháŋ" } }));

        /// <summary>
        /// Gets Week <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Week { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Week,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Week,
                RelativeTimeStyleValues.Long,
                "Okó",
                new Dictionary<int, string> { { -1, "Okó kʼuŋ héhaŋ" }, { 0, "Lé okó kiŋ" }, { 1, "Tȟokáta okó kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta okó {0} kʼuŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ okó {0} kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Week,
                RelativeTimeStyleValues.Narrow,
                "Okó",
                new Dictionary<int, string> { { -1, "Okó kʼuŋ héhaŋ" }, { 0, "Lé okó kiŋ" }, { 1, "Tȟokáta okó kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta okó {0} kʼuŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ okó {0} kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Week,
                RelativeTimeStyleValues.Short,
                "Okó",
                new Dictionary<int, string> { { -1, "Okó kʼuŋ héhaŋ" }, { 0, "Lé okó kiŋ" }, { 1, "Tȟokáta okó kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta okó {0} kʼuŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ okó {0} kiŋháŋ" } }));

        /// <summary>
        /// Gets WeekOfMonth <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource WeekOfMonth { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.WeekOfMonth,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.WeekOfMonth,
                RelativeTimeStyleValues.Long,
                "Week Of Month",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.WeekOfMonth,
                RelativeTimeStyleValues.Narrow,
                "Week Of Month",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.WeekOfMonth,
                RelativeTimeStyleValues.Short,
                "Week Of Month",
                null,
                null,
                null));

        /// <summary>
        /// Gets Day <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Day { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Day,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Day,
                RelativeTimeStyleValues.Long,
                "Aŋpétu",
                new Dictionary<int, string> { { -1, "Ȟtálehaŋ" }, { 0, "Lé aŋpétu kiŋ" }, { 1, "Híŋhaŋni kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta {0}-čháŋ k’uŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ {0}-čháŋ kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Day,
                RelativeTimeStyleValues.Narrow,
                "Aŋpétu",
                new Dictionary<int, string> { { -1, "Ȟtálehaŋ" }, { 0, "Lé aŋpétu kiŋ" }, { 1, "Híŋhaŋni kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta {0}-čháŋ k’uŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ {0}-čháŋ kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Day,
                RelativeTimeStyleValues.Short,
                "Aŋpétu",
                new Dictionary<int, string> { { -1, "Ȟtálehaŋ" }, { 0, "Lé aŋpétu kiŋ" }, { 1, "Híŋhaŋni kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta {0}-čháŋ k’uŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ {0}-čháŋ kiŋháŋ" } }));

        /// <summary>
        /// Gets DayOfYear <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource DayOfYear { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.DayOfYear,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.DayOfYear,
                RelativeTimeStyleValues.Long,
                "Day Of Year",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.DayOfYear,
                RelativeTimeStyleValues.Narrow,
                "Day Of Year",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.DayOfYear,
                RelativeTimeStyleValues.Short,
                "Day Of Year",
                null,
                null,
                null));

        /// <summary>
        /// Gets Weekday <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Weekday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Weekday,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Weekday,
                RelativeTimeStyleValues.Long,
                "Okó-aŋpétu",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Weekday,
                RelativeTimeStyleValues.Narrow,
                "Okó-aŋpétu",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Weekday,
                RelativeTimeStyleValues.Short,
                "Okó-aŋpétu",
                null,
                null,
                null));

        /// <summary>
        /// Gets WeekdayOfMonth <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource WeekdayOfMonth { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.WeekdayOfMonth,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.WeekdayOfMonth,
                RelativeTimeStyleValues.Long,
                "Weekday Of Month",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.WeekdayOfMonth,
                RelativeTimeStyleValues.Narrow,
                "Weekday Of Month",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.WeekdayOfMonth,
                RelativeTimeStyleValues.Short,
                "Weekday Of Month",
                null,
                null,
                null));

        /// <summary>
        /// Gets Sunday <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Sunday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Sunday,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Sunday,
                RelativeTimeStyleValues.Long,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétuwakȟáŋ kʼuŋ héhaŋ" }, { 0, "Aŋpétuwakȟáŋ kiŋ lé" }, { 1, "Aŋpétuwakȟáŋ kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Sundays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Sundays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Sunday,
                RelativeTimeStyleValues.Narrow,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétuwakȟáŋ kʼuŋ héhaŋ" }, { 0, "Aŋpétuwakȟáŋ kiŋ lé" }, { 1, "Aŋpétuwakȟáŋ kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Sundays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Sundays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Sunday,
                RelativeTimeStyleValues.Short,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétuwakȟáŋ kʼuŋ héhaŋ" }, { 0, "Aŋpétuwakȟáŋ kiŋ lé" }, { 1, "Aŋpétuwakȟáŋ kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Sundays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Sundays" } }));

        /// <summary>
        /// Gets Monday <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Monday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Monday,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Monday,
                RelativeTimeStyleValues.Long,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétutȟokahe kʼuŋ héhaŋ" }, { 0, "Aŋpétutȟokahe kiŋ lé" }, { 1, "Aŋpétutȟokahe kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Mondays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Mondays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Monday,
                RelativeTimeStyleValues.Narrow,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétutȟokahe kʼuŋ héhaŋ" }, { 0, "Aŋpétutȟokahe kiŋ lé" }, { 1, "Aŋpétutȟokahe kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Mondays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Mondays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Monday,
                RelativeTimeStyleValues.Short,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétutȟokahe kʼuŋ héhaŋ" }, { 0, "Aŋpétutȟokahe kiŋ lé" }, { 1, "Aŋpétutȟokahe kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Mondays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Mondays" } }));

        /// <summary>
        /// Gets Tuesday <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Tuesday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Tuesday,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Tuesday,
                RelativeTimeStyleValues.Long,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétunuŋpa kʼuŋ héhaŋ" }, { 0, "Aŋpétunuŋpa kiŋ lé" }, { 1, "Aŋpétunuŋpa kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Tuesdays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Tuesdays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Tuesday,
                RelativeTimeStyleValues.Narrow,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétunuŋpa kʼuŋ héhaŋ" }, { 0, "Aŋpétunuŋpa kiŋ lé" }, { 1, "Aŋpétunuŋpa kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Tuesdays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Tuesdays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Tuesday,
                RelativeTimeStyleValues.Short,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétunuŋpa kʼuŋ héhaŋ" }, { 0, "Aŋpétunuŋpa kiŋ lé" }, { 1, "Aŋpétunuŋpa kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Tuesdays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Tuesdays" } }));

        /// <summary>
        /// Gets Wednesday <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Wednesday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Wednesday,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Wednesday,
                RelativeTimeStyleValues.Long,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétuyamni kʼuŋ héhaŋ" }, { 0, "Aŋpétuyamni kiŋ lé" }, { 1, "Aŋpétuyamni kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Wednesdays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Wednesdays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Wednesday,
                RelativeTimeStyleValues.Narrow,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétuyamni kʼuŋ héhaŋ" }, { 0, "Aŋpétuyamni kiŋ lé" }, { 1, "Aŋpétuyamni kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Wednesdays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Wednesdays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Wednesday,
                RelativeTimeStyleValues.Short,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétuyamni kʼuŋ héhaŋ" }, { 0, "Aŋpétuyamni kiŋ lé" }, { 1, "Aŋpétuyamni kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Wednesdays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Wednesdays" } }));

        /// <summary>
        /// Gets Thursday <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Thursday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Thursday,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Thursday,
                RelativeTimeStyleValues.Long,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétutopa kʼuŋ héhaŋ" }, { 0, "Aŋpétutopa kiŋ lé" }, { 1, "Aŋpétutopa kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Thursdays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Thursdays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Thursday,
                RelativeTimeStyleValues.Narrow,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétutopa kʼuŋ héhaŋ" }, { 0, "Aŋpétutopa kiŋ lé" }, { 1, "Aŋpétutopa kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Thursdays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Thursdays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Thursday,
                RelativeTimeStyleValues.Short,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétutopa kʼuŋ héhaŋ" }, { 0, "Aŋpétutopa kiŋ lé" }, { 1, "Aŋpétutopa kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Thursdays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Thursdays" } }));

        /// <summary>
        /// Gets Friday <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Friday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Friday,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Friday,
                RelativeTimeStyleValues.Long,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétuzaŋptaŋ kʼuŋ héhaŋ" }, { 0, "Apétuzaptaŋ kiŋ lé" }, { 1, "Aŋpétuzaptaŋ kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Fridays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Fridays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Friday,
                RelativeTimeStyleValues.Narrow,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétuzaŋptaŋ kʼuŋ héhaŋ" }, { 0, "Apétuzaptaŋ kiŋ lé" }, { 1, "Aŋpétuzaptaŋ kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Fridays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Fridays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Friday,
                RelativeTimeStyleValues.Short,
                null,
                new Dictionary<int, string> { { -1, "Aŋpétuzaŋptaŋ kʼuŋ héhaŋ" }, { 0, "Apétuzaptaŋ kiŋ lé" }, { 1, "Aŋpétuzaptaŋ kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Fridays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Fridays" } }));

        /// <summary>
        /// Gets Saturday <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Saturday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Saturday,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Saturday,
                RelativeTimeStyleValues.Long,
                null,
                new Dictionary<int, string> { { -1, "Owáŋkayužažapi kʼuŋ héhaŋ" }, { 0, "Owáŋkayužažapi kiŋ lé" }, { 1, "Owáŋkayužažapi kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Saturdays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Saturdays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Saturday,
                RelativeTimeStyleValues.Narrow,
                null,
                new Dictionary<int, string> { { -1, "Owáŋkayužažapi kʼuŋ héhaŋ" }, { 0, "Owáŋkayužažapi kiŋ lé" }, { 1, "Owáŋkayužažapi kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Saturdays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Saturdays" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Saturday,
                RelativeTimeStyleValues.Short,
                null,
                new Dictionary<int, string> { { -1, "Owáŋkayužažapi kʼuŋ héhaŋ" }, { 0, "Owáŋkayužažapi kiŋ lé" }, { 1, "Owáŋkayužažapi kiŋháŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "-{0} Saturdays" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "+{0} Saturdays" } }));

        /// <summary>
        /// Gets DayPeriod <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource DayPeriod { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.DayPeriod,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.DayPeriod,
                RelativeTimeStyleValues.Long,
                "Dayperiod",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.DayPeriod,
                RelativeTimeStyleValues.Narrow,
                "Dayperiod",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.DayPeriod,
                RelativeTimeStyleValues.Short,
                "Dayperiod",
                null,
                null,
                null));

        /// <summary>
        /// Gets Hour <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Hour { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Hour,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Hour,
                RelativeTimeStyleValues.Long,
                "Owápȟe",
                new Dictionary<int, string> { { 0, "this hour" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta owápȟe {0} kʼuŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ owápȟe {0} kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Hour,
                RelativeTimeStyleValues.Narrow,
                "Owápȟe",
                new Dictionary<int, string> { { 0, "this hour" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta owápȟe {0} kʼuŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ owápȟe {0} kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Hour,
                RelativeTimeStyleValues.Short,
                "Owápȟe",
                new Dictionary<int, string> { { 0, "this hour" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta owápȟe {0} kʼuŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ owápȟe {0} kiŋháŋ" } }));

        /// <summary>
        /// Gets Minute <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Minute { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Minute,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Minute,
                RelativeTimeStyleValues.Long,
                "Owápȟe oȟʼáŋkȟo",
                new Dictionary<int, string> { { 0, "this minute" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta oȟ’áŋkȟo {0} k’uŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ oȟ’áŋkȟo {0} kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Minute,
                RelativeTimeStyleValues.Narrow,
                "Owápȟe oȟʼáŋkȟo",
                new Dictionary<int, string> { { 0, "this minute" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta oȟ’áŋkȟo {0} k’uŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ oȟ’áŋkȟo {0} kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Minute,
                RelativeTimeStyleValues.Short,
                "Owápȟe oȟʼáŋkȟo",
                new Dictionary<int, string> { { 0, "this minute" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta oȟ’áŋkȟo {0} k’uŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ oȟ’áŋkȟo {0} kiŋháŋ" } }));

        /// <summary>
        /// Gets Second <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Second { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Second,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Second,
                RelativeTimeStyleValues.Long,
                "Okpí",
                new Dictionary<int, string> { { 0, "now" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta okpí {0} k’uŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ okpí {0} kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Second,
                RelativeTimeStyleValues.Narrow,
                "Okpí",
                new Dictionary<int, string> { { 0, "now" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta okpí {0} k’uŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ okpí {0} kiŋháŋ" } }),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Second,
                RelativeTimeStyleValues.Short,
                "Okpí",
                new Dictionary<int, string> { { 0, "now" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Hékta okpí {0} k’uŋ héhaŋ" } },
                new Dictionary<PluralRulesValues, string> { { PluralRulesValues.Other, "Letáŋhaŋ okpí {0} kiŋháŋ" } }));

        /// <summary>
        /// Gets Zone <see cref="IRelativeTimeStylesResource"/> for 'Lakota' [lkt]
        /// </summary>
        public IRelativeTimeStylesResource Zone { get; } = new RelativeTimeStylesResource(
            LOCALE,
            RelativeTimeUnitValues.Zone,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Zone,
                RelativeTimeStyleValues.Long,
                "Zone",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Zone,
                RelativeTimeStyleValues.Narrow,
                "Zone",
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeUnitValues.Zone,
                RelativeTimeStyleValues.Short,
                "Zone",
                null,
                null,
                null));

        /// <summary>
        /// Gets the Relative Time resource styles based on the unit specified
        /// </summary>
        /// <param name="relativeTimeUnit">The resource unit to get</param>
        /// <returns>An <see cref="IRelativeTimeStylesResource"/></returns>
        /// <exception cref="RelativeTimeUnitNotFoundException"></exception>
        public IRelativeTimeStylesResource GetRelativeTimeStylesResource(RelativeTimeUnitValues relativeTimeUnit) => relativeTimeUnit switch
        {
            RelativeTimeUnitValues.Era => this.Era,
            RelativeTimeUnitValues.Year => this.Year,
            RelativeTimeUnitValues.Quarter => this.Quarter,
            RelativeTimeUnitValues.Month => this.Month,
            RelativeTimeUnitValues.Week => this.Week,
            RelativeTimeUnitValues.WeekOfMonth => this.WeekOfMonth,
            RelativeTimeUnitValues.Day => this.Day,
            RelativeTimeUnitValues.DayOfYear => this.DayOfYear,
            RelativeTimeUnitValues.Weekday => this.Weekday,
            RelativeTimeUnitValues.WeekdayOfMonth => this.WeekdayOfMonth,
            RelativeTimeUnitValues.Sunday => this.Sunday,
            RelativeTimeUnitValues.Monday => this.Monday,
            RelativeTimeUnitValues.Tuesday => this.Tuesday,
            RelativeTimeUnitValues.Wednesday => this.Wednesday,
            RelativeTimeUnitValues.Thursday => this.Thursday,
            RelativeTimeUnitValues.Friday => this.Friday,
            RelativeTimeUnitValues.Saturday => this.Saturday,
            RelativeTimeUnitValues.DayPeriod => this.DayPeriod,
            RelativeTimeUnitValues.Hour => this.Hour,
            RelativeTimeUnitValues.Minute => this.Minute,
            RelativeTimeUnitValues.Second => this.Second,
            RelativeTimeUnitValues.Zone => this.Zone,
            _ => throw new RelativeTimeUnitNotFoundException("Relative time unit does not exists", nameof(relativeTimeUnit))
        };
    }
}