//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Script: ./scripts/cldr-relative-time.csx
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Alrev.Intl.Abstractions;
using Alrev.Intl.Abstractions.RelativeTime;
using System;

namespace Alrev.Intl.RelativeTime.Resources
{
    public class LowerSorbianRelativeTimeResourceSet : IRelativeTimeResourceSet, IResource
    {
        private const string LOCALE = "dsb";
        public string Locale { get; } = LOCALE;

        public IRelativeTimeStylesResource Era { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "epocha",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "epocha",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "epocha",
                null,
                null,
                null,
                null,
                null));

        public IRelativeTimeStylesResource Year { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "lěto",
                "łoni",
                "lětosa",
                "znowa",
                new RelativeTimeCountResource("pśed {0} lětom", "pśed {0} lětami"),
                new RelativeTimeCountResource("za {0} lěto", "za {0} lět")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "l.",
                "łoni",
                "lětosa",
                "znowa",
                new RelativeTimeCountResource("pśed {0} l.", "pśed {0} l."),
                new RelativeTimeCountResource("za {0} l.", "za {0} l.")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "l.",
                "łoni",
                "lětosa",
                "znowa",
                new RelativeTimeCountResource("pśed {0} l.", "pśed {0} l."),
                new RelativeTimeCountResource("za {0} l.", "za {0} l.")));

        public IRelativeTimeStylesResource Quarter { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "kwartal",
                "last quarter",
                "this quarter",
                "next quarter",
                new RelativeTimeCountResource("pśed {0} kwartalom", "pśed {0} kwartalami"),
                new RelativeTimeCountResource("za {0} kwartal", "za {0} kwartalow")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "kw.",
                "last quarter",
                "this quarter",
                "next quarter",
                new RelativeTimeCountResource("pśed {0} kw.", "pśed {0} kw."),
                new RelativeTimeCountResource("za {0} kw.", "za {0} kw.")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "kwart.",
                "last quarter",
                "this quarter",
                "next quarter",
                new RelativeTimeCountResource("pśed {0} kwart.", "pśed {0} kwart."),
                new RelativeTimeCountResource("za {0} kwart.", "za {0} kwart.")));

        public IRelativeTimeStylesResource Month { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "mjasec",
                "slědny mjasec",
                "ten mjasec",
                "pśiducy mjasec",
                new RelativeTimeCountResource("pśed {0} mjasecom", "pśed {0} mjasecami"),
                new RelativeTimeCountResource("za {0} mjasec", "za {0} mjasecow")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "mjas.",
                "slědny mjasec",
                "ten mjasec",
                "pśiducy mjasec",
                new RelativeTimeCountResource("pśed {0} mjas.", "pśed {0} mjas."),
                new RelativeTimeCountResource("za {0} mjas.", "za {0} mjas.")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "mjas.",
                "slědny mjasec",
                "ten mjasec",
                "pśiducy mjasec",
                new RelativeTimeCountResource("pśed {0} mjas.", "pśed {0} mjas."),
                new RelativeTimeCountResource("za {0} mjas.", "za {0} mjas.")));

        public IRelativeTimeStylesResource Week { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "tyźeń",
                "slědny tyźeń",
                "ten tyźeń",
                "pśiducy tyźeń",
                new RelativeTimeCountResource("pśed {0} tyźenjom", "pśed {0} tyźenjami"),
                new RelativeTimeCountResource("za {0} tyźeń", "za {0} tyźenjow")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "tyź.",
                "slědny tyźeń",
                "ten tyźeń",
                "pśiducy tyźeń",
                new RelativeTimeCountResource("pśed {0} tyź.", "pśed {0} tyź."),
                new RelativeTimeCountResource("za {0} tyź.", "za {0} tyź.")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "tyź.",
                "slědny tyźeń",
                "ten tyźeń",
                "pśiducy tyźeń",
                new RelativeTimeCountResource("pśed {0} tyź.", "pśed {0} tyź."),
                new RelativeTimeCountResource("za {0} tyź.", "za {0} tyź.")));

        public IRelativeTimeStylesResource WeekOfMonth { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "Week Of Month",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "Week Of Month",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "Week Of Month",
                null,
                null,
                null,
                null,
                null));

        public IRelativeTimeStylesResource Day { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "źeń",
                "cora",
                "źinsa",
                "witśe",
                new RelativeTimeCountResource("pśed {0} dnjom", "pśed {0} dnjami"),
                new RelativeTimeCountResource("za {0} źeń", "za {0} dnjow")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "ź",
                "cora",
                "źinsa",
                "witśe",
                new RelativeTimeCountResource("pśed {0} d", "pśed {0} d"),
                new RelativeTimeCountResource("za {0} ź", "za {0} ź")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "źeń",
                "cora",
                "źinsa",
                "witśe",
                new RelativeTimeCountResource("pśed {0} dnj.", "pśed {0} dnj."),
                new RelativeTimeCountResource("za {0} źeń", "za {0} dnj.")));

        public IRelativeTimeStylesResource DayOfYear { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "Day Of Year",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "Day Of Year",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "Day Of Year",
                null,
                null,
                null,
                null,
                null));

        public IRelativeTimeStylesResource Weekday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "źeń tyźenja",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "źeń tyźenja",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "źeń tyźenja",
                null,
                null,
                null,
                null,
                null));

        public IRelativeTimeStylesResource WeekdayOfMonth { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "Weekday Of Month",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "Weekday Of Month",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "Weekday Of Month",
                null,
                null,
                null,
                null,
                null));

        public IRelativeTimeStylesResource Sunday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "slědnu njeźelu",
                "tu njeźelu",
                "pśiducu njeźelu",
                new RelativeTimeCountResource(null, "-{0} Sundays"),
                new RelativeTimeCountResource(null, "+{0} Sundays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "slědnu nj.",
                "tu nj.",
                "pśiducu nj.",
                new RelativeTimeCountResource(null, "-{0} Sundays"),
                new RelativeTimeCountResource(null, "+{0} Sundays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "slědnu nje.",
                "tu nje.",
                "pśiducu nje.",
                new RelativeTimeCountResource(null, "-{0} Sundays"),
                new RelativeTimeCountResource(null, "+{0} Sundays")));

        public IRelativeTimeStylesResource Monday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "slědne pónjeźele",
                "to pónjeźele",
                "pśiduce pónjeźele",
                new RelativeTimeCountResource(null, "-{0} Mondays"),
                new RelativeTimeCountResource(null, "+{0} Mondays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "slědne pó.",
                "to pó.",
                "pśiduce pó.",
                new RelativeTimeCountResource(null, "-{0} Mondays"),
                new RelativeTimeCountResource(null, "+{0} Mondays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "slědne pónj.",
                "to pónj.",
                "pśiduce pónj.",
                new RelativeTimeCountResource(null, "-{0} Mondays"),
                new RelativeTimeCountResource(null, "+{0} Mondays")));

        public IRelativeTimeStylesResource Tuesday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "slědnu wałtoru",
                "tu wałtoru",
                "pśiducu wałtoru",
                new RelativeTimeCountResource(null, "-{0} Tuesdays"),
                new RelativeTimeCountResource(null, "+{0} Tuesdays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "slědnu wa.",
                "tu wa.",
                "pśiducu wa.",
                new RelativeTimeCountResource(null, "-{0} Tuesdays"),
                new RelativeTimeCountResource(null, "+{0} Tuesdays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "slědnu wałt.",
                "tu wałt.",
                "pśiducu wałt.",
                new RelativeTimeCountResource(null, "-{0} Tuesdays"),
                new RelativeTimeCountResource(null, "+{0} Tuesdays")));

        public IRelativeTimeStylesResource Wednesday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "slědnu srjodu",
                "tu srjodu",
                "pśiducu srjodu",
                new RelativeTimeCountResource(null, "-{0} Wednesdays"),
                new RelativeTimeCountResource(null, "+{0} Wednesdays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "slědnu sr.",
                "tu sr.",
                "pśiducu sr.",
                new RelativeTimeCountResource(null, "-{0} Wednesdays"),
                new RelativeTimeCountResource(null, "+{0} Wednesdays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "slědnu srj.",
                "tu srj.",
                "pśiducu srj.",
                new RelativeTimeCountResource(null, "-{0} Wednesdays"),
                new RelativeTimeCountResource(null, "+{0} Wednesdays")));

        public IRelativeTimeStylesResource Thursday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "slědny stwórtk",
                "ten stwórtk",
                "pśiducy stwórtk",
                new RelativeTimeCountResource(null, "-{0} Thursdays"),
                new RelativeTimeCountResource(null, "+{0} Thursdays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "slědny st.",
                "ten st.",
                "pśiducy st.",
                new RelativeTimeCountResource(null, "-{0} Thursdays"),
                new RelativeTimeCountResource(null, "+{0} Thursdays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "slědny stw.",
                "ten stw.",
                "pśiducy stw.",
                new RelativeTimeCountResource(null, "-{0} Thursdays"),
                new RelativeTimeCountResource(null, "+{0} Thursdays")));

        public IRelativeTimeStylesResource Friday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "slědny pětk",
                "ten pětk",
                "pśiducy pětk",
                new RelativeTimeCountResource(null, "-{0} Fridays"),
                new RelativeTimeCountResource(null, "+{0} Fridays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "slědny pě.",
                "ten pě.",
                "pśiducy pě.",
                new RelativeTimeCountResource(null, "-{0} Fridays"),
                new RelativeTimeCountResource(null, "+{0} Fridays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "slědny pět.",
                "ten pět.",
                "pśiducy pět.",
                new RelativeTimeCountResource(null, "-{0} Fridays"),
                new RelativeTimeCountResource(null, "+{0} Fridays")));

        public IRelativeTimeStylesResource Saturday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "slědnu sobotu",
                "tu sobotu",
                "pśiducu sobotu",
                new RelativeTimeCountResource(null, "-{0} Saturdays"),
                new RelativeTimeCountResource(null, "+{0} Saturdays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "slědnu so.",
                "tu so.",
                "pśiducu so.",
                new RelativeTimeCountResource(null, "-{0} Saturdays"),
                new RelativeTimeCountResource(null, "+{0} Saturdays")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "slědnu sob.",
                "tu sob.",
                "pśiducu sob.",
                new RelativeTimeCountResource(null, "-{0} Saturdays"),
                new RelativeTimeCountResource(null, "+{0} Saturdays")));

        public IRelativeTimeStylesResource DayPeriod { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "połojca dnja",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "połojca dnja",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "połojca dnja",
                null,
                null,
                null,
                null,
                null));

        public IRelativeTimeStylesResource Hour { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "góźina",
                null,
                "this hour",
                null,
                new RelativeTimeCountResource("pśed {0} góźinu", "pśed {0} góźinami"),
                new RelativeTimeCountResource("za {0} góźinu", "za {0} góźin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "g",
                null,
                "this hour",
                null,
                new RelativeTimeCountResource("pśed {0} g", "pśed {0} g"),
                new RelativeTimeCountResource("za {0} g", "za {0} g")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "góź.",
                null,
                "this hour",
                null,
                new RelativeTimeCountResource("pśed {0} góź.", "pśed {0} góź."),
                new RelativeTimeCountResource("za {0} góź.", "za {0} góź.")));

        public IRelativeTimeStylesResource Minute { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "minuta",
                null,
                "this minute",
                null,
                new RelativeTimeCountResource("pśed {0} minutu", "pśed {0} minutami"),
                new RelativeTimeCountResource("za {0} minutu", "za {0} minutow")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "m",
                null,
                "this minute",
                null,
                new RelativeTimeCountResource("pśed {0} m", "pśed {0} m"),
                new RelativeTimeCountResource("za {0} m", "za {0} m")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "min.",
                null,
                "this minute",
                null,
                new RelativeTimeCountResource("pśed {0} min.", "pśed {0} min."),
                new RelativeTimeCountResource("za {0} min.", "za {0} min.")));

        public IRelativeTimeStylesResource Second { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "sekunda",
                null,
                "now",
                null,
                new RelativeTimeCountResource("pśed {0} sekundu", "pśed {0} sekundami"),
                new RelativeTimeCountResource("za {0} sekundu", "za {0} sekundow")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "s",
                null,
                "now",
                null,
                new RelativeTimeCountResource("pśed {0} s", "pśed {0} s"),
                new RelativeTimeCountResource("za {0} s", "za {0} s")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "sek.",
                null,
                "now",
                null,
                new RelativeTimeCountResource("pśed {0} sek.", "pśed {0} sek."),
                new RelativeTimeCountResource("za {0} sek.", "za {0} sek.")));

        public IRelativeTimeStylesResource Zone { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "casowe pasmo",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "casowe pasmo",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "casowe pasmo",
                null,
                null,
                null,
                null,
                null));
    }
}