//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Script: ./scripts/cldr-relative-time.csx
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Alrev.Intl.Abstractions;
using Alrev.Intl.Abstractions.RelativeTime;
using System;

namespace Alrev.Intl.RelativeTime.Resources
{
    public class UzbekRelativeTimeResourceSet : IRelativeTimeResourceSet, IResource
    {
        private const string LOCALE = "uz-Latn";
        public string Locale { get; } = LOCALE;

        public IRelativeTimeStylesResource Era { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "era",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "era",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "era",
                null,
                null,
                null,
                null,
                null));

        public IRelativeTimeStylesResource Year { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "yil",
                "o‘tgan yil",
                "shu yil",
                "keyingi yil",
                new RelativeTimeCountResource("{0} yil oldin", "{0} yil oldin"),
                new RelativeTimeCountResource("{0} yildan keyin", "{0} yildan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "yil",
                "o‘tgan yil",
                "bu yil",
                "keyingi yil",
                new RelativeTimeCountResource("{0} yil oldin", "{0} yil oldin"),
                new RelativeTimeCountResource("{0} yildan keyin", "{0} yildan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "yil",
                "o‘ʻtgan yil",
                "bu yil",
                "keyingi yil",
                new RelativeTimeCountResource("{0} yil oldin", "{0} yil oldin"),
                new RelativeTimeCountResource("{0} yildan keyin", "{0} yildan keyin")));

        public IRelativeTimeStylesResource Quarter { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "chorak",
                "o‘tgan chorak",
                "shu chorak",
                "keyingi chorak",
                new RelativeTimeCountResource("{0} chorak oldin", "{0} chorak oldin"),
                new RelativeTimeCountResource("{0} chorakdan keyin", "{0} chorakdan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "ch",
                "o‘tgan chorak",
                "shu chorak",
                "keyingi chorak",
                new RelativeTimeCountResource("{0} chorak oldin", "{0} chorak oldin"),
                new RelativeTimeCountResource("{0} chorakdan keyin", "{0} chorakdan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "ch",
                "o‘tgan chorak",
                "shu chorak",
                "keyingi chorak",
                new RelativeTimeCountResource("{0} chorak oldin", "{0} chorak oldin"),
                new RelativeTimeCountResource("{0} chorakdan keyin", "{0} chorakdan keyin")));

        public IRelativeTimeStylesResource Month { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "oy",
                "o‘tgan oy",
                "shu oy",
                "keyingi oy",
                new RelativeTimeCountResource("{0} oy oldin", "{0} oy oldin"),
                new RelativeTimeCountResource("{0} oydan keyin", "{0} oydan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "oy",
                "o‘tgan oy",
                "bu oy",
                "keyingi oy",
                new RelativeTimeCountResource("{0} oy oldin", "{0} oy oldin"),
                new RelativeTimeCountResource("{0} oydan keyin", "{0} oydan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "oy",
                "o‘tgan oy",
                "bu oy",
                "keyingi oy",
                new RelativeTimeCountResource("{0} oy oldin", "{0} oy oldin"),
                new RelativeTimeCountResource("{0} oydan keyin", "{0} oydan keyin")));

        public IRelativeTimeStylesResource Week { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "hafta",
                "o‘tgan hafta",
                "shu hafta",
                "keyingi hafta",
                new RelativeTimeCountResource("{0} hafta oldin", "{0} hafta oldin"),
                new RelativeTimeCountResource("{0} haftadan keyin", "{0} haftadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "hafta",
                "o‘tgan hafta",
                "bu hafta",
                "keyingi hafta",
                new RelativeTimeCountResource("{0} hafta oldin", "{0} hafta oldin"),
                new RelativeTimeCountResource("{0} haftadan keyin", "{0} haftadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "hafta",
                "o‘tgan hafta",
                "bu hafta",
                "keyingi hafta",
                new RelativeTimeCountResource("{0} hafta oldin", "{0} hafta oldin"),
                new RelativeTimeCountResource("{0} haftadan keyin", "{0} haftadan keyin")));

        public IRelativeTimeStylesResource WeekOfMonth { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "oyning haftasi",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "oyning haftasi",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "oyning haftasi",
                null,
                null,
                null,
                null,
                null));

        public IRelativeTimeStylesResource Day { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "kun",
                "kecha",
                "bugun",
                "ertaga",
                new RelativeTimeCountResource("{0} kun oldin", "{0} kun oldin"),
                new RelativeTimeCountResource("{0} kundan keyin", "{0} kundan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "kun",
                "kecha",
                "bugun",
                "ertaga",
                new RelativeTimeCountResource("{0} kun oldin", "{0} kun oldin"),
                new RelativeTimeCountResource("{0} kundan keyin", "{0} kundan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "kun",
                "kecha",
                "bugun",
                "ertaga",
                new RelativeTimeCountResource("{0} kun oldin", "{0} kun oldin"),
                new RelativeTimeCountResource("{0} kundan keyin", "{0} kundan keyin")));

        public IRelativeTimeStylesResource DayOfYear { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "yilning kuni",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "yilning kuni",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "yilning kuni",
                null,
                null,
                null,
                null,
                null));

        public IRelativeTimeStylesResource Weekday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "hafta kuni",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "hafta kuni",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "hafta kuni",
                null,
                null,
                null,
                null,
                null));

        public IRelativeTimeStylesResource WeekdayOfMonth { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "oyning hafta kuni",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "oyning hafta kuni",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "oyning hafta kuni",
                null,
                null,
                null,
                null,
                null));

        public IRelativeTimeStylesResource Sunday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "o‘tgan yakshanba",
                "shu yakshanba",
                "keyingi yakshanba",
                new RelativeTimeCountResource("{0} ta yakshanba oldin", "{0} ta yakshanba oldin"),
                new RelativeTimeCountResource("{0} ta yakshanbadan keyin", "{0} ta yakshanbadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "o‘tgan yakshanba",
                "shu yakshanba",
                "keyingi yakshanba",
                new RelativeTimeCountResource("{0} ta yakshanba oldin", "{0} ta yakshanba oldin"),
                new RelativeTimeCountResource("{0} ta yakshanbadan keyin", "{0} ta yakshanbadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "o‘tgan yakshanba",
                "shu yakshanba",
                "keyingi yakshanba",
                new RelativeTimeCountResource("{0} ta yakshanba oldin", "{0} ta yakshanba oldin"),
                new RelativeTimeCountResource("{0} ta yakshanbadan keyin", "{0} ta yakshanbadan keyin")));

        public IRelativeTimeStylesResource Monday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "o‘tgan dushanba",
                "shu dushanba",
                "keyingi dushanba",
                new RelativeTimeCountResource("{0} ta dushanba oldin", "{0} ta dushanba oldin"),
                new RelativeTimeCountResource("{0} ta dushanbadan keyin", "{0} ta dushanbadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "o‘tgan dushanba",
                "shu dushanba",
                "keyingi dushanba",
                new RelativeTimeCountResource("{0} ta dushanba oldin", "{0} ta dushanba oldin"),
                new RelativeTimeCountResource("{0} ta dushanbadan keyin", "{0} ta dushanbadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "o‘tgan dushanba",
                "shu dushanba",
                "keyingi dushanba",
                new RelativeTimeCountResource("{0} ta dushanba oldin", "{0} ta dushanba oldin"),
                new RelativeTimeCountResource("{0} ta dushanbadan keyin", "{0} ta dushanbadan keyin")));

        public IRelativeTimeStylesResource Tuesday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "o‘tgan seshanba",
                "shu seshanba",
                "keyingi seshanba",
                new RelativeTimeCountResource("{0} ta seshanba oldin", "{0} ta seshanba oldin"),
                new RelativeTimeCountResource("{0} ta seshanbadan keyin", "{0} ta seshanbadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "o‘tgan seshanba",
                "shu seshanba",
                "keyingi seshanba",
                new RelativeTimeCountResource("{0} ta seshanba oldin", "{0} ta seshanba oldin"),
                new RelativeTimeCountResource("{0} ta seshanbadan keyin", "{0} ta seshanbadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "o‘tgan seshanba",
                "shu seshanba",
                "keyingi seshanba",
                new RelativeTimeCountResource("{0} ta seshanba oldin", "{0} ta seshanba oldin"),
                new RelativeTimeCountResource("{0} ta seshanbadan keyin", "{0} ta seshanbadan keyin")));

        public IRelativeTimeStylesResource Wednesday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "o‘tgan chorshanba",
                "shu chorshanba",
                "keyingi chorshanba",
                new RelativeTimeCountResource("{0} ta chorshanba oldin", "{0} ta chorshanba oldin"),
                new RelativeTimeCountResource("{0} ta chorshanbadan keyin", "{0} ta chorshanbadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "o‘tgan chorshanba",
                "shu chorshanba",
                "keyingi chorshanba",
                new RelativeTimeCountResource("{0} ta chorshanba oldin", "{0} ta chorshanba oldin"),
                new RelativeTimeCountResource("{0} ta chorshanbadan keyin", "{0} ta chorshanbadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "o‘tgan chorshanba",
                "shu chorshanba",
                "keyingi chorshanba",
                new RelativeTimeCountResource("{0} ta chorshanba oldin", "{0} ta chorshanba oldin"),
                new RelativeTimeCountResource("{0} ta chorshanbadan keyin", "{0} ta chorshanbadan keyin")));

        public IRelativeTimeStylesResource Thursday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "o‘tgan payshanba",
                "shu payshanba",
                "keyingi payshanba",
                new RelativeTimeCountResource("{0} ta payshanba oldin", "{0} ta payshanba oldin"),
                new RelativeTimeCountResource("{0} ta payshanbadan keyin", "{0} ta payshanbadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "o‘tgan payshanba",
                "shu payshanba",
                "keyingi payshanba",
                new RelativeTimeCountResource("{0} ta payshanba oldin", "{0} ta payshanba oldin"),
                new RelativeTimeCountResource("{0} ta payshanbadan keyin", "{0} ta payshanbadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "o‘tgan payshanba",
                "shu payshanba",
                "keyingi payshanba",
                new RelativeTimeCountResource("{0} ta payshanba oldin", "{0} ta payshanba oldin"),
                new RelativeTimeCountResource("{0} ta payshanbadan keyin", "{0} ta payshanbadan keyin")));

        public IRelativeTimeStylesResource Friday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "o‘tgan juma",
                "shu juma",
                "keyingi juma",
                new RelativeTimeCountResource("{0} ta juma oldin", "{0} ta juma oldin"),
                new RelativeTimeCountResource("{0} ta jumadan keyin", "{0} ta jumadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "o‘tgan juma",
                "shu juma",
                "keyingi juma",
                new RelativeTimeCountResource("{0} ta juma oldin", "{0} ta juma oldin"),
                new RelativeTimeCountResource("{0} ta jumadan keyin", "{0} ta jumadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "o‘tgan juma",
                "shu juma",
                "keyingi juma",
                new RelativeTimeCountResource("{0} ta juma oldin", "{0} ta juma oldin"),
                new RelativeTimeCountResource("{0} ta jumadan keyin", "{0} ta jumadan keyin")));

        public IRelativeTimeStylesResource Saturday { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                null,
                "o‘tgan shanba",
                "shu shanba",
                "keyingi shanba",
                new RelativeTimeCountResource("{0} ta shanba oldin", "{0} ta shanba oldin"),
                new RelativeTimeCountResource("{0} ta shanbadan keyin", "{0} ta shanbadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                null,
                "o‘tgan shanba",
                "shu shanba",
                "keyingi shanba",
                new RelativeTimeCountResource("{0} ta shanba oldin", "{0} ta shanba oldin"),
                new RelativeTimeCountResource("{0} ta shanbadan keyin", "{0} ta shanbadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                null,
                "o‘tgan shanba",
                "shu shanba",
                "keyingi shanba",
                new RelativeTimeCountResource("{0} ta shanba oldin", "{0} ta shanba oldin"),
                new RelativeTimeCountResource("{0} ta shanbadan keyin", "{0} ta shanbadan keyin")));

        public IRelativeTimeStylesResource DayPeriod { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "TO/TK",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "TO/TK",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "TO/TK",
                null,
                null,
                null,
                null,
                null));

        public IRelativeTimeStylesResource Hour { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "soat",
                null,
                "shu soatda",
                null,
                new RelativeTimeCountResource("{0} soat oldin", "{0} soat oldin"),
                new RelativeTimeCountResource("{0} soatdan keyin", "{0} soatdan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "soat",
                null,
                "shu soatda",
                null,
                new RelativeTimeCountResource("{0} soat oldin", "{0} soat oldin"),
                new RelativeTimeCountResource("{0} soatdan keyin", "{0} soatdan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "soat",
                null,
                "shu soatda",
                null,
                new RelativeTimeCountResource("{0} soat oldin", "{0} soat oldin"),
                new RelativeTimeCountResource("{0} soatdan keyin", "{0} soatdan keyin")));

        public IRelativeTimeStylesResource Minute { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "daqiqa",
                null,
                "shu daqiqada",
                null,
                new RelativeTimeCountResource("{0} daqiqa oldin", "{0} daqiqa oldin"),
                new RelativeTimeCountResource("{0} daqiqadan keyin", "{0} daqiqadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "daq.",
                null,
                "shu daqiqada",
                null,
                new RelativeTimeCountResource("{0} daqiqa oldin", "{0} daqiqa oldin"),
                new RelativeTimeCountResource("{0} daqiqadan keyin", "{0} daqiqadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "daq.",
                null,
                "shu daqiqada",
                null,
                new RelativeTimeCountResource("{0} daqiqa oldin", "{0} daqiqa oldin"),
                new RelativeTimeCountResource("{0} daqiqadan keyin", "{0} daqiqadan keyin")));

        public IRelativeTimeStylesResource Second { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "soniya",
                null,
                "hozir",
                null,
                new RelativeTimeCountResource("{0} soniya oldin", "{0} soniya oldin"),
                new RelativeTimeCountResource("{0} soniyadan keyin", "{0} soniyadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "son.",
                null,
                "hozir",
                null,
                new RelativeTimeCountResource("{0} soniya oldin", "{0} soniya oldin"),
                new RelativeTimeCountResource("{0} soniyadan keyin", "{0} soniyadan keyin")),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "son.",
                null,
                "hozir",
                null,
                new RelativeTimeCountResource("{0} soniya oldin", "{0} soniya oldin"),
                new RelativeTimeCountResource("{0} soniyadan keyin", "{0} soniyadan keyin")));

        public IRelativeTimeStylesResource Zone { get; } = new RelativeTimeStylesResource(
            LOCALE,
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Long,
                "vaqt mintaqasi",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Narrow,
                "vaqt mintaqasi",
                null,
                null,
                null,
                null,
                null),
            new RelativeTimeResource(
                LOCALE,
                RelativeTimeTypeValues.Short,
                "vaqt mintaqasi",
                null,
                null,
                null,
                null,
                null));
    }
}